services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk
      POSTGRES_DB: helpdesk
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U helpdesk -d helpdesk']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: '3000'
      DATABASE_URL: postgresql://helpdesk:helpdesk@postgres:5432/helpdesk?schema=public
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      JWT_SECRET: ${JWT_SECRET:-dev-only-change-me}
      JWT_EXPIRES_IN: 1h
      BUSINESS_TIMEZONE: Europe/Belgrade
      BUSINESS_START_HOUR: '9'
      BUSINESS_END_HOUR: '17'
      BUSINESS_WORKDAYS: 1,2,3,4,5
      BUSINESS_HOLIDAYS: ''
      SLA_SCAN_INTERVAL_MS: '60000'
      SEED_ON_BOOT: ${SEED_ON_BOOT:-true}
    ports:
      - '3000:3000'

  prometheus:
    image: prom/prometheus:v3.1.0
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - promdata:/prometheus
    ports:
      - '9090:9090'
    depends_on:
      - api

  grafana:
    image: grafana/grafana:11.5.2
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_USERS_DEFAULT_THEME: dark
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/helpdesk.json
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafanadata:/var/lib/grafana
    ports:
      - '3003:3000'
    depends_on:
      - prometheus

volumes:
  pgdata:
  redisdata:
  promdata:
  grafanadata:
